config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :lectures do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  validates :title, :description, :price, :youtube_url, presence: true
  validates :description, length: { minimum: 6 }
  has_one_attached :photo
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :lecture
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  has_many :lectures, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one_attached :photo

  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

   def configure_permitted_parameters
     # For additional fields in app/views/devise/registrations/new.html.erb
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

     # For additional in app/views/devise/registrations/edit.html.erb
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
   end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    if params[:query].present?
      @lectures = Lecture.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @lectures = Lecture.all
    end
  end

  def show
    @lecture = Lecture.find(params[:id])
  end

  def new
    @lecture = Lecture.new
  end

  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.user = current_user

    if @lecture.save
      redirect_to @lecture, notice: 'Lecture was successfully created.'
    else
      render :new
    end
  end

  def update
    @lecture = Lecture.find(params[:id])
    if @lecture.update(lecture_params)
      redirect_to @lecture, notice: 'Lecture was successfully updated!'
    else
      render :edit
    end
  end

  def edit
    @lecture = Lecture.find(params[:id])
  end

  def destroy
    @lecture = Lecture.find(params[:id])
    @lecture.destroy
    redirect_to lectures_path(@lecture)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def lecture_params
    params.require(:lecture).permit(:title, :description, :price, :youtube_url, :photo)
  end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_lecture, except: :show

  def show
    @order = Order.find(params[:id])

  end

  def new
    @lecture = Lecture.find(params[:lecture_id])
  end

  def create
    @lecture = Lecture.find(params[:lecture_id])
    @order = Order.new(lecture: @lecture, user: current_user)
    if @order.save
      redirect_to order_path(@order), alert: "Order created"
    else
      render :new
    end
  end

  def destroy
    @order.destroy
    redirect_to lectures_path(@lecture)
  end

  private

  def order_params
    params.require(:order).permit(:new, :create)
  end

  def set_lecture
    @lecture = Lecture.find(params[:lecture_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :configure_permitted_parameters, if: :devise_controller?

  def home
    @lectures = Lecture.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hobbyshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%# render 'shared/button' %>
    <%= render 'shared/flashes' %>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/lectures/_form.html.erb
<%= simple_form_for(@lectures) do |f| %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<div class="container-form">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="form-login">
      <h2>Edit your Lecture</h2>

      <%= simple_form_for(@lecture) do |f| %>
        <%# f.error_notification %>
        <%# f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :youtube_url %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: "btn btn-primary mt-3"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lectures/index.html.erb
<div class="banner_index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('https://images.pexels.com/photos/5905716/pexels-photo-5905716.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1') %>);">
  <div class="w-50">
    <h1><strong>Want to share your hobby?</strong></h1>
    <%= link_to "Create Your Lecture", new_lecture_path, class: "btn btn-primary mt-3" %>
  </div>
</div>

<div class="d-flex justify-content-between my-3 mx-3">
  <div class="row">
    <% @lectures.each do |lecture|%>
      <div class= "col-4 mb-4">
        <div class="card-product pl-4 mx-1">
        <% if lecture.photo.attached? %>
          <%= cl_image_tag(lecture.photo.key) %>
        <% else %>
          <img src="https://images.pexels.com/photos/1655304/pexels-photo-1655304.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" />
        <% end %>
          <div class="card-product-infos">
            <h2><%= lecture.title %></h2>
            <%= link_to "Discover our course", lecture_path(lecture), class: "btn btn-ghost mt-2" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lectures/new.html.erb
<div class= "background d-flex justify-content-center">
  <div class= "create-form container w-50 p-5 ">

    <h2>Upload your Lecture</h2>

    <%= simple_form_for(@lecture) do |f| %>
      <%# f.error_notification %>
      <%# f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :youtube_url %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn btn-primary mt-3 w-100"%>


    <% end %>

  </div>
</div>

app/views/lectures/show.html.erb
<div class="banner_index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('show-lecture.jpg') %>);">
  <div class="w-40">
  </div>
</div>

<div class="container my-5">
  <div class="row justify-content-center">
    <div class="box-description col-8 d-flex flex-column justify-content-between">
    <div>
      <h1><strong><%= @lecture.title %></strong>
        <% if @lecture.user == current_user %>
          <%= link_to edit_lecture_path(@lecture) do %>
            <i class="fas fa-pencil-alt"></i>
          <% end %>
          <%= link_to lecture_path(@lecture), method: :delete, data: { confirm: "Are you sure?"} do %>
          <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </h1>
      <h4> <%= @lecture.description %></h4>
      <h4>R$ <%= @lecture.price %></h4>
    </div>
      <div class="links">
        <div class="d-flex justify-content-between ">
          <%= link_to lectures_path do %>
            <i class="fas fa-angle-double-left"></i>
          <% end %>
          <% if @lecture.user != current_user %>
            <%= link_to 'Buy', new_lecture_order_path(@lecture), class: "btn btn-primary my-3"%>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card-trip-small">
        <% if @lecture.photo.key %>
          <%= cl_image_tag @lecture.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <img src="https://images.pexels.com/photos/7859276/pexels-photo-7859276.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" />
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container">
  <div class="card mx-auto col-6 mt-5">
    <div class="card-body">
      <h2><%= @lecture.title %></h2>
      <h4>R$ <%= @lecture.price %></h4>
      <div class="d-flex w-100 ms-5">
          <%= link_to lecture_path(@lecture) do %>
            <i class="fas fa-angle-double-left"></i>
        <% end %>
        <div class="button-order">
          <%= link_to "Confirm purchase", lecture_orders_path(@lecture), method: :post, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container mt-5 d-flex flex-column justify-content-center align-items-center">
  <h3> Your Order </h3>
  <div class="container">
    <div class="row py-3 d-flex flex-column justify-content-center align-items-center">
      <div class="col-8">
        <div class="card-product-order">
          <% if @order.lecture.photo.attached? %>
            <%= cl_image_tag(@order.lecture.photo.key) %>
          <% else %>
            <%= image_tag('10.jpg')%>
          <% end %>
          <div class="card-product-infos d-flex flex-column justify-content-center align-items-center my-2">
            <h4><strong>Congratulation ! </strong></h4>
            <h5><strong>You Can Watch Your Video </strong></h5>
            <h6 class="text-center m-0"><%= @order.lecture.title %></h6>
            <p class="text-center m-0"><%= @order.lecture.description %></p>
            <h5 class="mt-2">R$ <%= @order.lecture.price %></h5>
            <h6><%= link_to "Watch Your Video", @order.lecture.youtube_url, target: "_blank"%></h6>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to lectures_path do %>
    <i class="fas fa-angle-double-left mb-5"></i>
    <% end %>
</div>

app/views/pages/edit.html.erb
<h2>Edit</h2>

<%= render 'form', garden: @lecture %>

app/views/pages/home.html.erb
<div class="banner"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("homepage.jpg") %>)">
  <div class="container">
    <h1><strong>Hobbyshare To Creative People</strong>!</h1>
  </div>
</div>

<div class="text-center mt-5 mb-5">
  <h1><strong>Discover Your New Hobby</strong></h1>
    <%= link_to "Learn more about", lectures_path, class: "btn btn-primary mt-3" %>
</div>

app/views/shared/_button.html.erb
<%= link_to "Search you lecture", "#", class: "btn btn-ghost" %>
<%= link_to "Book now", "#", class: "btn btn-flat" %>
<%= link_to "Start now", "#", class: "btn btn-gradient" %>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= image_tag "8.png", width: 50, class: "mt-2" %>
  <div class="footer-copyright">
    HobbyShare
  </div>
  <div>
    This project was built by women <i class="fas fa-heart"></i>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>